# Generated by Django 6.1.1 on 2026-09-05 01:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_child', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('laundry', 'Laundry'), ('living', 'Living areas'), ('bedrooms', 'Bedrooms'), ('outdoor', 'Outdoor'), ('pets', 'Pets'), ('errands', 'Errands')], default='kitchen', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='chores.chore')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='chores.member')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='chores.member')),
            ],
            options={
                'ordering': ['due_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('finished', 'Finished')], max_length=20)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chores.chore')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chores.member')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='chores.chore')),
            ],
            options={
                'unique_together': {('chore', 'kind')},
            },
        ),
    ]
