# Generated by Django 6.1.1 on 2026-09-05 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_name', models.CharField(max_length=120)),
                ('points', models.PositiveSmallIntegerField()),
                ('pauses', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(choices=[('completed', 'Completed'), ('reclaimed', 'Reclaimed')], default='completed', max_length=20)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='chores.member')),
            ],
            options={
                'ordering': ['-awarded_at', '-id'],
            },
        ),
    ]
