# Generated by Django 6.1.1 on 2026-09-05 01:41

from django.db import migrations, models


def backfill_chore_points(apps, schema_editor):
    """Rows written before the snapshot existed: the live chore is the best guess."""
    PointsAward = apps.get_model("chores", "PointsAward")
    awards = []
    for award in PointsAward.objects.select_related("chore"):
        award.chore_points = award.chore.points if award.chore else award.points
        awards.append(award)
    PointsAward.objects.bulk_update(awards, ["chore_points"])


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_pointsaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsaward',
            name='chore_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_chore_points, migrations.RunPython.noop),
    ]
